sudo: required

services:
  - docker

script:
  - docker build --no-cache -f Dockerfile -t micanzhang/bazel-golang .
  - docker run --rm  -it  -v $PWD/examples:/root/examples  -w "/root/examples" micanzhang/bazel-golang make run
